@isTest
public class WeekResearchTriggerTest {
    static testMethod void testTriggerMethod(){
		// Week_Research__c wr = new Week_Research__c();
        // //wr.Start_Date__c = Date.valueOf('2022-02-07');
        // //wr.End_Date__c = Date.valueOf('2022-02-13') ;
        // wr.DuplicateRemark__c = 'test';
        // wr.IsActive__c  = True;
		// test.startTest();
        // INSERT wr;
		// test.stopTest();  
    }
}